name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your branch is different

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Upload Frontend Files
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./HotelClientAPI  # Ensure this is your frontend folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
